image:
  file: .gitpod.Dockerfile

tasks:
  - init: sudo /etc/init.d/mysql start && ./mvnw install -DskipTests=false
  - name: MySQL Server
    command: docker run --rm -d -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=alurafood-pagamento -e MYSQL_USER=root -e MYSQL_PASSWORD=root -p 3306:3306 mysql:latest

ports:
  - port: 8080
    onOpen: open-preview
  - port: 3306
